#!/usr/bin/env mksh

# required for:                       compiling c                compiling bmake    compiling bmake     compiling 99% of c code
packages=('filesystem' 'sbase-static' 'tcc-static' 'mksh-static' 'diffutils-static' 'onetrueawk-static' 'musl' 'cproc-static' 'qbe-static')
rm -rfv chroot

cd packages || exit 1

  for package in "${packages[@]}"; do

    cd "$package" || exit 1

      ../../buildapex || exit 1

    cd ..

  done

cd ..

mkdir -v chroot

cd chroot || exit 1

  for package in "${packages[@]}"; do

    tar xvf ../packages/${package}/*.tar.lz

  done

  ln -vs /usr/bin/mksh usr/bin/sh
  ln -vs /usr/bin/cproc usr/bin/cc

cd ..